version: '3.8'

services:
  # Development service
  app-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: magnify-modal-reveal-dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  # Production service
  app-prod:
    build: .
    container_name: magnify-modal-reveal-prod
    ports:
      - "80:80"
    restart: unless-stopped
