name: Docker Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and test development image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.dev
        push: false
        tags: magnify-modal-reveal-dev:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build and test production image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: magnify-modal-reveal:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
